# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' dijkstra algorithm
#' @param adj_matrix the adjacency matrix
#' @param starting the starting vertex we want to run the algorithm from
#' @return a 2*n matrix (first row : the best distance from the starting vertex vector , second row : the previous vertex vector)
dijkstraAlgorithm <- function(adj_matrix, starting) {
    .Call(`_MedHardGSOC_dijkstraAlgorithm`, adj_matrix, starting)
}

